### ISSUE TITLE
我 把 这 个 插 件 提 交 到 了 utools 上

### ISSUE THREAD

**Issue by slblog-github** [kexingfu/utools-plugin-text2image#2]
kexingfu大佬好,我 把 这 个 插 件 提 交 到 了 utools 上。
![image](https://user-images.githubusercontent.com/64446074/106888676-de887a80-6721-11eb-80ba-6dfdec013ccd.png)

**Comment by zhheo** [comment]
我看插件中心本来就有啊，我看到的是你提交的吗
![image](https://user-images.githubusercontent.com/33177975/106896844-13e69580-672d-11eb-9d56-89c8485f5baa.png)

**Comment by slblog-github** [comment]
> 我看插件中心本来就有啊，我看到的是你提交的吗
> ![image](https://user-images.githubusercontent.com/33177975/106896844-13e69580-672d-11eb-9d56-89c8485f5baa.png)

大概喽,我这里显示审核通过

**Comment by slblog-github** [comment]
> > 我看插件中心本来就有啊，我看到的是你提交的吗
> > ![image](https://user-images.githubusercontent.com/33177975/106896844-13e69580-672d-11eb-9d56-89c8485f5baa.png)
> 
> 大概喽,我这里显示审核通过

好吧不是的(
